global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'meli-proxy'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
